WEG-419: compatibility cordova9
WEGOTRADE/me.apla.cordova.app-preferences pull request #3
Opened 2019-08-28 11:56 UTC by JonathanLefebvre

I did a pull from this guy  https://github.com/NemSavic/me.apla.cordova.app-preferences who did the update to cordova 9 and other tweak. He did a pull request for the main repo, but still not merge...

2019-08-28 12:05 UTC, JonathanLefebvre commented
There 3 `.yml` config file who is useless to us. I am not sure if we keep it or not.

2019-08-28 13:47 UTC, jrobichaud requested changes
Sorry, French ahead:

Raisons fréquentes pour faire un fork:

1. pour soumettre une PR à une autre librairie et d’avoir le fix le temps que ça soit mergé.
2. pour avoir une copie figée dans le temps au cas qu’un dude efface le repository (pour éviter des sagas comme ça: https://qz.com/646467/how-one-programmer-broke-the-internet-by-deleting-a-tiny-piece-of-code/). Malgré ça il est possible qu’un fork devienne brisé à cause d’une de ses dépendances ou une de ses dépendances de ses dépendances qui disparaît alors ce n’est pas du tout infaillible (tout comme la saga left-pad). Cette copie est identique à l’original.
3. Pour faire des changements propriétaires et ainsi diverger de la version maintenue. Il faut être très rigoureux sur comment maintenir le code. À faire en dernier recours.

This PR will diverge from the original repositories and create confusion on future maintenance of the code. I would recommend to base our code on a fork of the branch of the guy.

Changes were made to a config file, should this be a PR made to the repository of NemSavic? Does this really change anything?

2019-08-28 17:49 UTC, JonathanLefebvre commented
Le problème avec me.apla.cordova.app-preferences est que l'auteur original ne s'en occupe pu.
Il nous faut pointé ailleurs que sur l'original. Ce qui est déjà fait, nous avons notre repo.
Je n'ai aucune garantie sur tout les fork qui existe présentement. Et pour les raison que tu énumères s'est préférable pour la compagnie d'avoir son fork.

Si la confusion que tu mentionnes ce produit, on avisera à ce moment là. Il y a des choses qui peuvent changer entre temps.

2019-09-03 14:38 UTC, jrobichaud commented
I ran a diff between both directories and the only differences are these:


diff nemsavic/package.json wgt/package.json

```diff
27c27
<     "elementtree": "^0.1.6",
---
>     "elementtree": "^0.1.7",
30c30
<     "xcode": "^0.8.2"
---
>     "xcode": "^2.0.0"
33c33
<     "cordova": ">=5.4.1",
---
>     "cordova": "^9.0.0",
```

Can you explain these changes?

2019-09-03 15:58 UTC, jrobichaud approved these changes

2019-09-03 15:59 UTC, merged

2019-09-03 17:17 UTC, JonathanLefebvre commented
> I ran a diff between both directories and the only differences are these:
> 
> diff nemsavic/package.json wgt/package.json
> 
> ```diff
> 27c27
> <     "elementtree": "^0.1.6",
> ---
> >     "elementtree": "^0.1.7",
> 30c30
> <     "xcode": "^0.8.2"
> ---
> >     "xcode": "^2.0.0"
> 33c33
> <     "cordova": ">=5.4.1",
> ---
> >     "cordova": "^9.0.0",
> ```
> 
> Can you explain these changes?

I update it to use the MacCloud version and the same as the mobile repo